        #include "Windows/Timer_InputPolling.cpp"
        #include "Windows/Timer_GlowAnimations.cpp"
        #include "Windows/Timer_StateTracking.cpp"
        #include "Windows/Timer_SmartRedraw.cpp"
        #include "Windows/Timer_DynamicTransparency.cpp"