#include "Windows/Timer/Timer_InputPolling.cpp"
#include "Windows/Timer/Timer_GlowAnimations.cpp"
#include "Windows/Timer/Timer_StateTracking.cpp"
#include "Windows/Timer/Timer_SmartRedraw.cpp"
#include "Windows/Timer/Timer_DynamicTransparency.cpp"