    #include "UI/Drawing/Drawing_HotkeyOverlay.cpp"
    #include "UI/Drawing/Drawing_HShifterRails.cpp"
    #include "UI/Drawing/Drawing_Gears.cpp"
    #include "UI/Drawing/Drawing_ReverseGear.cpp"
    #include "UI/Drawing/Drawing_GhostKnob.cpp"
    #include "UI/Drawing/Drawing_MainKnob.cpp"
    #include "UI/Drawing/Drawing_IndicatorBars.cpp"