#include "Input/Submodules/XInput_Rumble.cpp"
#include "Input/Submodules/XInput_Knob_Prefix.cpp"
#include "Input/Submodules/XInput_Knob_Physics.cpp"
#include "Input/Submodules/XInput_Knob_Transparency.cpp"
#include "Input/Submodules/XInput_vJoy.cpp"